---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-service-discovery
spec:
  redirectRegex:
    permanent: true
    regex: /.well-known/(card|cal)dav
    replacement: /remote.php/dav/

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-{{ include "team-nextcloud.fullname" . }}
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.app.name }}.{{ .Values.app.domain }}`)
      kind: Rule
      services:
        - name: {{ include "team-nextcloud.fullname" . }}-nc
          port: 80
      middlewares:
        - name: nextcloud-service-discovery
  tls:
    certResolver: default
