app:
  name: cloud
  domain: example.org

# Set a username and password for the first administrator account:
admin:
  name: admin
  password: secret

# storage limit for nextcloud files and database
storage:
  limits:
    data: 128Gi
    database: 128Gi

# no need to change these values. For internal databas account only
database:
  password: "secret#password"
  root_password: "very123secret#passWord!"
