# Domain and subdomain for this service:
app:
  name: chat
  domain: example.org

# Set a username and password for the first administrator account:
admin:
  name: admin
  password: secret
  mail: admin@example.org

# Storage limit for files and database (no need to change):
storage:
  limits:
    data: 128Gi
    database: 128Gi